---
- name: test if mount_requests is set correctly
  assert:
    that:
      - mount_requests is defined
      - mount_requests | length > 0
      - mount_requests is iterable
    quiet: yes

- name: test if item.backup in mount_requests is set correctly
  assert:
    that:
      - item.backup is boolean
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - item.backup is defined

- name: test if item.boot in mount_requests is set correctly
  assert:
    that:
      - item.boot is boolean
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - item.boot is defined

- name: test if item.dump in mount_requests is set correctly
  assert:
    that:
      - item.dump | length > 0
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - item.dump is defined

- name: test if item.fstab in mount_requests is set correctly
  assert:
    that:
      - item.fstab | length > 0
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - item.fstab is defined

- name: test if item.fstype in mount_requests is set correctly
  assert:
    that:
      - item.fstype | length > 0
      - item.fstype in [ "ext3", "ext4", "iso9660", "nfs", "none", "xfs" ]
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - item.fstype is defined

- name: test if item.opts in mount_requests is set correctly
  assert:
    that:
      - item.opts | length > 0
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - item.opts is defined

- name: test if item.passno in mount_requests is set correctly
  assert:
    that:
      - item.passno | length > 0
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - item.passno is defined

- name: test if item.path in mount_requests is set correctly
  assert:
    that:
      - item.path is defined
      - item.path | length > 0
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"

- name: test if item.src in mount_requests is set correctly
  assert:
    that:
      - item.src | length > 0
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - item.src is defined

- name: test if item.state in mount_requests is set correctly
  assert:
    that:
      - item.state is defined
      - item.state | length > 0
      - item.state in [ "absent", "mounted", "present", "remounted", "unmounted" ]
    quiet: yes
  loop: "{{ mount_requests }}"
  loop_control:
    label: "{{ item.path }}"
